TEORIE
x = 2 y = 3 n = 2 x + y # Adunare x - y # Scadere x * y # Inmultire x ** y # Ridicare la putere <=> x^y in C++ x / y # Impartire x // y # Impartire cu trunchiere, rezultatul e nr. intreg x % y # Operatia modulo - rezultatul va fi restul lui x / y pow(x, y) # x^y abs(x) # Modulul lui x round(x) # Rotunjeste pe x, rezultat nr. intreg round(x, n) # Rotunjeste pe x la n zecimala bin(x) # x in baza 2 (binar) hex(x) # x in baza 16 (hexa) range(10) # numerele intregi de la 0 la 9 range(1, 10) # numerele intregi de la 1 la 9 range(0, 10, 2) # numerele intregi de la 0 la 9 din 2 in 2: 0, 2, 4, 6, 8 print(x) # cout<<x - Afisare x = input() # cin>>x - Atribuire ceva in x x = int(x) # In x punem ce am atribuit sub forma de val. intreaga x = float(x) # In x punem ce am atribuit sub forma de val. flotanta (nr real) x = str(x) # In x punem ce am atribuit sub forma de sir de caractere # OBSERVATIE: O sa vedeti ca asa lucram si cu LISTE, TUPLE si SETURI, # trecand de la un tip de date la altul in mod convenabil. nume = "Vladut Vacaru" ## Metode de slicing pentru siruri de caractere nume[2] # a (numaratoarea incepe de la 0!) nume[:] # Vladut Vacaru (afiseaza intreg sirul) nume[1:] # ladut Vacaru (afiseaza de la caracterul de pe poz 1 inclusiv, incolo) nume[:2] # Vl (afiseaza pana la pozitia 2 inclusiv) nume[-1] # u (afiseaza caracterul de pe ultima pozitie) nume[-2] # r (afiseaza caracterul de pe penultima pozitie) nume[::2] # Vau aau (afiseaza caracterele din 2 in 2) nume[::-1] # uracaV tudalV (afiseaza in ordine inversa - functie speciala) nume[0:8:2] # Vau (nume[start:stop:step] adica iau caracterele de la pozitia start inclusiv, pana la stop (stop nu se include), cu pasul step) ## Observatii: Endline-ul se pune automat, nu mai e necesar, cum era in C sa il punem dupa fiecare print ## dar, daca se doreste endl in mod specific -> print("\n") # Concatenare - op. + intre siruri print("Ion " + nume) # Ion Vladut Vacaru # Afisare multipla print(nume * 10) # Vladut Vacaru va fi afisat de 10 ori len(nume) # Numarul de caractere din sir, inclusiv spatiile nume.strip() # Sterge spatiile care sunt la inceput si final, nu si cele din interiorul sirului nume.split() # Genereaza o lista cu toate cuvintele din sir, despartite prin spatiu # OBS: la split, putem adauga "," sau "." in cazul in care pe post de despartitor avem altceva. Daca nu punem nimic, se considera spatiul ca vin despartitor. nume.replace("Vladut", "Ion") # Ion Vacaru (inlocuieste Vladut cu Ion)
nume.startswith("Vladut") # Adev. (puteti sa verificati si cu un singur caracter daca incepe) nume.endswith("Vacaru") # Adev. (la fel, puteti sa verificati si cu un sigur caracter daca se termina) nume.index("V") # pozitia unde se gaseste prima data caracterul V, daca nu gaseste da eroare nume.find("V") # pozitia unde se gaseste prima data caracterul V, daca nu gaseste da -1 nume.count("a") # numarul de aparitii al caracterului a, se poate face si pentru secvente de caractere nume.lower() # vladut vacaru (litere mici) nume.upper() # VLADUT VACARU (litere mari) nume.capitalize() # Vladut vacaru (bun pentru propozitii - incepe cu litera mare si restul pune litera mica) # Ca metoda de afisare in cazul mai multor siruri de caractere sau tipuri de date, recomand urmatoarea forma: print(f"Ma numesc {nume} si am {y} ani.") ## In cazul variabilelor boolene, bool(x) returneaza FALSE numai pentru x = None/False/CEVA NUL (0, lista goala, set gol etc.) lista = [1, 2, 3, 4] len(lista) # 4 - nr elemente din lista lista.index(3) # 2 - pozitia unde se afla elementul 3 lista.count(3) # 1 - nr aparitii ale elementului 3 lista[2] # 3 - elementul de pe pozitia 2 ## Observatie - Slicing-ul listelor se face IDEM elementelor de tip sir de caractere ## Adaugare in liste lista * 2 # elementele din lista de 2 ori lista + [100, 200] # adaugam la lista elementele 100, 200, putem adauga si un singur element (atentie, nu modifica lista denumita "lista") lista.append(100) # adaugam lista elementul 100, aici are loc modificarea listei "lista". atentie, nu putem adauga o intreaga lista dintr-o bucata ca mai sus. # ci adaugam element cu element. lista.extend([100, 200]) # adaugam in lista elementele 100 si 200, lucru care nu se poate cu append. lista se modifica lista.insert(2, "Inserez pe pozitia 2 acest text") # insereaza elementul de dupa virgula pe pozitia dorita si muta celelalte elemente ' '.join(["Vladut", "Vacaru"]) # Creez un sir de caractere cu elementele din lista (trebuie sa fie de tip string), iar inainte de join pun ce vreau sa desparta elementele (spatiu in acest caz) ## Stergere din liste lista.pop() # Stergem ultimul element lista.pop(1) # Stergem elementul de pe pozitia 1 lista.remove(4) # Stergem din lista elementul dintre paranteze la prima lui aparitie #lista.clear() # Stergem toate elementele din lista #del lista # Stergem existenta listei din memorie ## Sortare liste #lista.sort() # Lista este sortata in ordine crescatoare/alfabetica (toate elementele de acelasi tip!) #lista.sort(reverse=True) # Sortata descrescator #lista.reverse() # Inverseaza pozitia elementelor din lista (in oglinda) #sorted(lista) # Se creaza o copie sortata a listei #reversed(lista) # Se creaza o copie inversata a listei ## Copierea unei liste listaCopie = lista.copy() 2
listaCopie = lista[:] ## OBS: Nu se face listaCopie = lista - deoarece prin aceasta linie, noi atribuim listei noi nu elementele din lista veche, ## ci chiar adresa acesteia. Ce inseamna? Fiind la aceasi adresa, daca "lista" sufera modificari, atunci le vom observa si in "listaCopie" ## Operatii cu liste 1 in lista # True daca 1 se gaseste in lista, altfel False #min(lista) # Minimul din lista #max(lista) # Maximul din lista #sum(lista) # Insumeaza elementele din lista (sa fie int sau foat) # Tuple = liste nemodificabile tuple = ('struguri', 'mere', 'pere', 'mere') ## Observatie - in cadrul tuplelor, nu putem adauga sau modifica elemente! Odata ce a fost creata asa ramane! ## Deci interzis tuple[1] = 'gutui' sau tuple.append('visine') tuple[0] # struguri - putem prelua elementele de pe pozitii dorite tuple[-1] # mere - elementul de pe ultima pozitie len(tuple) # 4 - numarul de elemente tuple.index('mere') # pozitia primei aparitii a elementului 'mere' tuple.count('mere') # numarul de aparitii a elementului 'mere' # Seturi = lista cu elemente unice set1 = set() set2 = {1, 2, 3} set1.add(1) # adaug elementul 1 set1.add(2) # adaug elementul 2 set1.add(2) # nu se modifica, deoarece 2 exista deja set1.remove(1) # sterge elementul 1, daca nu exista 1 da eroare set1.discard(1) # sterge elementul 1, daca nu exista 1 nu se intampla nimic set1.clear() # elementele din set sunt sterse set1 = set2.copy() # copiem, situatie similara cu listele set3 = set1.union(set2) # set3 este reuniunea dintre set1 si set2 (elemente comune si necomune, scrise o singura data) set4 = set1.intersection(set2) # set4 este intersectia dintre set1 si set2 (elementele comune) set5 = set1.difference(set2) # sterge elementele ce se gasesc in set1 cat si in set2 si raman celelalte din set1 set6 = set1.symmetric_difference(set2) # sterge elementele ce se gasesc in set1 cat si in set2 si raman celelalte din ambele seturi set1.issubset(set2) # true daca set1 se gaseste integral in set2, false altfel set1.issuperset(set2) # true daca set2 se gaseste integral in set1, false altfel set1.isdisjoint(set2) # true daca set1 si set2 nu au niciun element comun, false altfel ## OBSERVATIE: Putem transforma convenabil listele, seturile si tuplele in ce dorim: set1 = list(set1) tuple = list(tuple) lista = set(lista) tuple = set(tuple) lista = tuple(lista) set1 = tuple(set1) 3
# Dictionare - perechi cheie valoare myDict = {'nume':'Vladut Vacaru', 'varsta':'90', 'situatie':'pensionar', 'in viata':True} myDict['nume'] # Vladut Vacaru - afisez cheia 'nume', daca nu exista cheia, da eroare len(myDict) # 4 - numarul de chei din dictionar list(myDict.keys()) # ['nume', 'varsta', 'situatie', 'in viata'] - afiseaza sub forma unei liste, cheile din dictionar list(myDict.values()) # ['Vladut Vacaru', '90', 'pensionar', True] - afiseaza sub forma unei liste, valorile cheilor din dictionar list(myDict.items()) # afiseaza sub forma de lista, perechi cheie-valoare myDict['par'] = 'carunt' # pot adauga in dict. pereche cheie ('par') valoare ('carunt') myDict.get('varsta') # 90 - asemanator cu myDict['varsta'], dar in acest caz daca nu exista cheia returneaza None myDict.get('prenume', 'NU EXISTA') # trimite valoarea cheii 'prenume', iar daca nu exista cheia, returneaza 'NU EXISTA' del myDict['nume'] # sterg efectiv din memorie cheia 'nume' a dictionarului myDict x == y # true daca egale x is y # true daca x si y sunt la aceeasi adresa! x is not y # true daca x si y nu sunt la aceeasi adresa x != y # true daca inegale x > y x < y x >= y x <= y and # se face intre 2 operatii, true daca ambele sunt adevarate or # la fel, returneaza true daca cel putin o conditie e indeplinita not True # da False x in lista # true daca x se afla in lista, false altfel x not in lista # true daca x nu se afla in lista, false altfel if x in lista: # program1 elif x in listaCopie: # program2 else: #program3 for nr in lista: # In nr se salveaza pe rand elementele din lista, pana la parcurgerea tuturor elementelor print(nr) # In final vor fi afisate toate elementele din lista, pe rand # Se aplica identic si la tuple, si la seturi pentru preluare element cu element for a, b in myDict.items(): # Preiau din dictionar pachet cheie-valoare print(a) # In a salvez cheia print(b) # In b salvez valoarea cheii a while x != y: # program if x < y: break # iese din bucla while else: continue # merge la linia urmatoare 4
# Functii def numeFunctie(x): return sum(x) print(numeFunctie([1,2,3])) ## *args - folosim pentru a trimite tuple ## **kwargs - folosim pentru a trimite dictionare def afisTuple(*tupla): for elem in tupla: print(elem) def afisDict(**dict): for cheie, val in dict.items(): print(f'{cheie} == {val}') tuple = ('struguri', 'mere', 'pere', 'mere') myDict = {'nume':'Vladut Vacaru', 'varsta':'90', 'situatie':'pensionar', 'in viata':True} afisTuple(*tuple) afisDict(**myDict) # LAMBDA Gauss = lambda n : n if n<=1 else n + Gauss(n-1) # Pentru un numar n trimis functiei Gauss, ia valoarea n pentru n<=1, altfel ia valoarea n + Gauss(n-1) - functie recursiva rezultat = Gauss(10) # aplic functia de mai sus pentru nr 10 print(rezultat) # MAP - aplica o functie pentru fiecare element dintr-o lista/set def cub(n): return n**3 numere = [1, 2, 3, 4] numereCub = map(cub, numere) # aplic functia cub pentru fiecare element al listei "numere" print(list(numereCub)) # transform in lista, altfel va afisa adresa # Filter - filtreaza valorile dupa o functie ce returneaza valoare tip boolean - true/false def numereMici(nr): if nr<30: return True else: return False import random numere = [random.randint(1,100) for _ in range(10)] #generez 10 numere pseudorandom intre 1 si 100 numereFiltrate = filter(numereMici, numere) # va selecta practic numerele mai mici decat 30 din lista 'numere' print(list(numereFiltrate)) # la fel, transformam in lista # Reduce - combina toate valorile si genereaza un singur rezultat final, bazat pe o functie, in general lambda import functools numere = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] 5
print(functools.reduce(lambda a, b: a + b, numere)) # 1 + 2 = 3; 3 + 3 = 6; 6 + 4 = 10; 10 + 5 = 15; etc.. Combina rezultatul cu urmatorul element! print(functools.reduce(lambda a, b: a if a>b else b, numere)) # afiseaza numarul maxim # Zip - pentru a intercala date dintre 2 liste / seturi / tuple de pe aceleasi pozitii si produce tupluri de elemente names = ['Ionescu', 'Popescu', 'Vasilescu'] ages = ['23', '32', '41'] for name, age in zip(names, ages): print(name, age) # Se va afisa pe rand: Ionescu 23 Popescu 32 Vasilescu 41 # Comprehensions - ajuta sa construim rapid liste, seturi, tuple, dictionare lista = [i for i in range(10)] # [0, 1, 2, ..., 9] set = {i for i in range(20) if i>=5} # {5, 6, 7, ..., 20} tuple = (i+2 for i in range(10)) # (2, 3, 4, 5, 6, 7, 8, 9, 10, 11) dict = {i: i*2 for i in range(10)} # {0: 0, 1: 2, 2: 4, ... , 9: 18}
6
PROBLEME REZOLVATE
1. Tricky picture: picture = [ [0,0,0,1,0,0,0], [0,0,1,1,1,0,0], [0,1,1,1,1,1,0], [1,1,1,1,1,1,1], [0,0,0,1,0,0,0], [0,0,0,1,0,0,0]]
Haha! Very funny, doamna Claudia! Nu e asa tricky pe cat ziceti dumneavoastra! Va afisa un BRAD FRUMOS! (poza din coltu’ dreapta sus)
# Rezolvare picture = [ [0,0,0,1,0,0,0], [0,0,1,1,1,0,0], [0,1,1,1,1,1,0], [1,1,1,1,1,1,1], [0,0,0,1,0,0,0], [0,0,0,1,0,0,0]] for line in picture: # Parcurg fiecare linie din lista de linii picture (e un fel de matrice) visual = " " # Creez o variabila in care practic voi salva linia modificata for element in line: # Parcurg fiecare element din linie if element == 1: visual = visual + '*' # Modific variabila de linie a.i. daca avem 1 pe o pozitie sa adauge * else: visual = visual + ' ' # Pentru 0, adauga un spatiu print(visual) # Inainte sa treaca la linia urmatoare, afisam linia curenta modificata
2. Scrieți un program care cere utilizatorului să introducă nota unui examen și afișează calificativul conform regulilor: ● 9-10: Excelent ● 7-8: Bine ● 5-6: Suficient ● Sub 5: Reexaminare Dacă utilizatorul introduce o notă invalidă (ex. -3 sau 11), cereți-i să reintroducă o valoare validă. # Rezolvare nota = input("Introduceti nota, domnule sutudent: ") # Introducem nota nota = int(nota) # Trebuie sa asiguram tipul de data, altfel programul nu va deosebi de string! if nota<1 or nota>10: # Mereu recomand a se verifica cazul care genereaza eroare si abia dupa cazurile okay! print("Din ce stiu notele in ROMANIA sunt intre 1 si 10!") elif nota>=9: # Nu am mai pus sa fie si mai mic decat 10, deoarece prin elif sugerez opusul conditiei de mai sus, adica nota<=10 print("Excelent! Esti un student model!") elif nota>=7: # La fel, nu mai fortez sa fie mai mic decat 9, elif imi asigura asta print("Bine dar se poate si mai bine!") elif nota>=5: print("Suficient, ma asteptam la mai mult!") else: print("REEXAMINARE! ESTI TUFA DE VENETIA!") 7
3. Scrieți un program care generează un număr aleatoriu între 1 și 50. Utilizatorul trebuie să ghicească numărul, iar programul oferă feedback: ● "Numărul este mai mare!" dacă utilizatorul a introdus un număr prea mic. ● "Numărul este mai mic!" dacă utilizatorul a introdus un număr prea mare. ● "Felicitări! Ai ghicit!" dacă numărul a fost găsit. # Rezolvare import random # Pentru valori aleatorii, trebuie import la fct. random numarAleator = random.randint(1,50) # General un nr pseudorandom intre 1 si 50 inclusiv numarAles = 0 # Initializez numarAles cu 0, care sigur nu e intre 1 si 50, pentru a face citirile in while strict while numarAles!=numarAleator: # Cat timp sunt diferite, stam in while numarAles=input("Introduceti numarul, domnule: ") # Numarul va fi introdus cat timp stam in bucla numarAles=int(numarAles) # Se transforma in int pentru a fi siguri ca nu este tratat ca string! if numarAles>numarAleator: # Verificam daca e mai mare, mai mic sau egal print("Numarul este mai mic!") elif numarAles<numarAleator: print("Numarul este mai mare!") else: print("FELICITARI! ATI GHICIT!")
4. Creați o listă de orașe și parcurgeți-o folosind enumerate(), astfel încât să afișați fiecare oraș numerotat. Exemplu de rulare: 1. București 2. Cluj-Napoca 3. Timișoara 4. Iași # Rezolvare orase = ['Bucuresti', 'Cluj-Napoca', 'Timisoara', 'Iasi'] # Creez lista conform cerintei for i, oras in enumerate(orase): # Aici i va fi ca un index, ia pozitia pentru fiecare element preluat din lista print(f"{i+1}. {oras}") # Am pus i+1, deoarece o lista incepe cu pozitia 0, si eu vreau sa am 1. Bucuresti 2. Cluj-Napoca...
8
5. Un utilizator participă la o loterie în care trebuie să aleagă un set de numere, iar programul generează numere câștigătoare. ● Utilizatorul își alege 6 numere între 1 și 49. ● Programul generează 6 numere aleatorii (simulând extragerea loteriei). ● Se compară numerele alese cu cele extrase. ● Se afișează câte numere a ghicit și un mesaj de câștig. Exemplu de rulare: Bine ai venit la Loteria Python! Alege 6 numere între 1 și 49. ● Numărul 1: 7 ● Numărul 2: 15 ● Numărul 3: 23 ● Numărul 4: 31 ● Numărul 5: 40 ● Numărul 6: 45
Numere extrase: [12, 7, 31, 23, 8, 40]
Ai ghicit 3 numere: [7, 23, 31]
Felicitări! Ai câștigat un premiu mic!
# Rezolvare import random # Declar liste necesare programului numereCastigatoare = [] numereAlese = [] numereGhicite = [] print('Bine ai venit la LOTO 6/49 \n') print('Alege 6 numere intre 1 si 49 \n') for i in range(6): # Pentru i de la 0 la 5, merg 6 pasi numarCurent = input(f'- Numarul {i+1}: ') # Am pus i+1 pentru ca i merge de la 0, si sa inceapa ordinea numerelor de la 1 numarCurent = int(numarCurent) # Mereu sa faceti trecerea la int, altfel va treziti cu string-uri! numereAlese.append(numarCurent) # Adaug in lista numarul curent selectat, la finalul for-ului voi avea toate cele 6 numere alese for i in range(6): numereCastigatoare.append(random.randint(1,49)) # Se simuleaza extragerea pe rand a unui numar aleatoriu intre 1 si 49 si il adaug in lista. for i in numereAlese: # Parcurg lista cu numere alese pentru a plasa in vectorul numereGhicite numerele alese care sunt si castigatoare if i in numereCastigatoare: # Daca numarul ales se afla in lista de numereCastigatoare, atunci adaug acel numar si in lista numereGhicite numereGhicite.append(i) print(f'Numere extrase: {numereAlese}') # Afisez numere extrase print(f'Ai ghicit {len(numereGhicite)} numere! {numereGhicite}') # Afisez nr de numere ghicite respectiv lista cu ele if len(numereGhicite) == 6: print("FELICITARI! ATI CASTIGAT PREMIUL CEL MARE!") elif len(numereGhicite) >= 4: print("Felicitari! Aticastigat un premiu mic") else: print("Ne pare rau! Ati pierdut! Mergeti acas'!") 9
6. Scrieți un program care simulează o aventură într-o pădure magică. Utilizatorul trebuie să aleagă între două direcții (stânga sau dreapta). În funcție de alegere, programul prezintă evenimente diferite (ex. întâlnirea unui lup, descoperirea unei comori). Adăugați mai multe evenimente, inclusiv un inventar pentru obiectele găsite.
Deja e vorba de creativitate. Creati liste cu evenimente, cream si un dictionar care e pe post de inventar sa zicem cu cheie armura, sabie, ce va vine in minte, iar ca valori ale acelor chei punem True/False. In rest, 1000 de if-uri, ca la parada! Puteti avea evenimente mai randomizate, sa folositi si functie de tip random.choice care sa aleaga un eveniment random din lista de evenimente creata de voi. Problema nu este dificila, doar necesita multa rabdare. Atasez exemplu cu AI:
import random # folosim random pentru evenimente aleatorii # dicționar cu evenimente posibile pe direcții evenimente = { "s": ["Ai întâlnit un lup 🐺", "Ai găsit o comoară 💰", "Ai căzut într-o groapă! 😵"], "d": ["Ai găsit o poiană 🌿", "Ai întâlnit un spiriduș 🧝", "Ai descoperit o peșteră 🕳️"] } # inventar sub formă de dicționar (obiect -> cantitate) inventar = {} print("🌲 Bine ai venit în Pădurea Magică!") print("Comenzi: s = stânga, d = dreapta, q = ieșire") # funcție mică pentru a adăuga obiecte în inventar def adauga_inventar(obiect): # dacă obiectul există deja în dicționar if obiect in inventar: inventar[obiect] += 1 # creștem cantitatea else: inventar[obiect] = 1 # îl adăugăm prima dată while True: # bucla principală a jocului alegere = input("\nAlege direcția (s/d/q): ") if alegere == "q": print("👋 Ai ieșit din pădure. Inventar final:", inventar) break if alegere in evenimente: # verificăm dacă e s sau d eveniment = random.choice(evenimente[alegere]) # alegem un eveniment random print("👉 Eveniment:", eveniment) # analizăm evenimentul și modificăm inventarul if "comoară" in eveniment: print("💰 Ai găsit aur!") adauga_inventar("aur") elif "spiriduș" in eveniment: print("🪄 Spiridușul ți-a dat o baghetă magică!") adauga_inventar("baghetă magică") elif "peșteră" in eveniment: print("🪨 Ai găsit o piatră misterioasă!") adauga_inventar("piatră misterioasă") elif "lup" in eveniment: print("🐺 Ai fugit de lup!") elif "groapă" in eveniment: print("😵 Ai căzut, dar te-ai ridicat!") # afișăm inventarul după fiecare pas print("🎒 Inventar:", inventar) else: print("❌ Comandă invalidă! Folosește s, d sau q.") 10
7. Creează un program care analizează tonul unui comentariu introdus de utilizator. ● Dacă un comentariu conține cuvinte pozitive (["bine", "frumos", "super", "excelent", "minunat"]), afișează "Comentariu pozitiv!". ● Dacă conține cuvinte negative (["urât", "prost", "groaznic", "dezamăgitor"]), afișează "Comentariu negativ!". ● Dacă nu se detectează niciun sentiment clar, afișează "Comentariu neutru.".
# Rezolvare comentariu = input('Ce mesaj transmiteti actualilor guvernanti ai Romaniei? Va rugam sa argumentati: ') # Definesc listele cu cuvintele aferente cuvintePozitive = ["bine", "frumos", "super", "excelent", "minunat"] cuvinteNegative = ["urat", "prost", "groaznic", "dezamăgitor"] if any(cuvant in comentariu.lower() for cuvant in cuvinteNegative): # Logica e: ia fiecare cuvant din lista cuvinteNegative si cauta daca se gaseste acea secventa in sirul de caractere "comentariu", # l-am pus lower pentru a ma asigura ca am idem cu ce se gaseste in lista cuvinteNegative print("Comentariu negativ!") elif any(cuvant in comentariu.lower() for cuvant in cuvintePozitive): # Logica e aceeasi, dar pentru lista cuvintePozitive print("Comentariu pozitiv!") else: print("Comentariu neutru.")
1. Creati un joc Rock-Paper-Scissors pentru doi jucatori. (Hint: Solicitati selectia jucatorilor (folosind input), comparati alegerile lor, afisati un mesaj de felicitari pentru castigator si intreabati daca jucatorii doresc sa inceapa un nou joc).
Tine minte regulile:
● Piatra bate foarfeca
● Foarfeca taie hartia
● Hartia bate piatra
# Rezolvare # Efectiv if-uri pentru toate cazurile! print("Bine ai venit la jocul Piatra-Hartie-Foarfeca!") Jucator1 = input("Jucator 1 alege: ") Jucator2 = input("Jucator 2 alege: ") if Jucator1.lower() == "piatra": if Jucator2.lower() == "piatra": print("REMIZA!") elif Jucator2.lower() == "hartie": print("Jucator 2 CASTIGA!") else: print("Jucator 1 CASTIGA!") if Jucator1.lower() == "hartie": if Jucator2.lower() == "piatra": print("Jucator 1 CASTIGA") elif Jucator2.lower() == "hartie": print("REMIZA!") else: print("Jucator 2 CASTIGA!") if Jucator1.lower() == "foarfeca": if Jucator2.lower() == "piatra": print("Jucator 2 CASTIGA") elif Jucator2.lower() == "hartie": print("Jucator 1 CASTIGA") else: print("REMIZA!") 11
2. Scrieti o funcție genereaza_factura() care acceptă numele clientului, și un număr variabil de produse și prețuri folosind **kwargs.
# Rezolvare def genereaza_factura(**kwargs): # La dictionare, folosim kwargs! for cheie, val in kwargs.items(): # Pentru a prelua perechea cheie-valoare, pe care le afisam print(f"{cheie}: {val}") cumparaturi_Popescu = {'Nume': 'Ionescu Popescu', 'Lapte': '10 RON', 'Piept de pui': '25 RON', 'WINSTON SLIM': '30 RON'} genereaza_factura(**cumparaturi_Popescu)
3. Scrieți o funcție care normalizează datele dintr-o listă într-un interval [0,1].
● Funcția trebuie să accepte o listă de numere și să returneze lista normalizată.
● Testați funcția pe un set de date aleator.
ex:data = [10, 20, 30, 40, 50]
normalized_data = normalize_data(data)
print(normalized_data) # Output: [0.0, 0.25, 0.5, 0.75, 1.0]
# Rezolvare def normalizare(dates): dates_new = [] maxim = max(dates) minim = min(dates) for data in dates: data_new = (data-minim)/(maxim-minim) # Pentru fiecare numar aplicam formula aceasta - formula standard pentru normalizare dates_new.append(data_new) return dates_new date = [10, 20, 30, 40, 50] date_normalizate = normalizare(date) print(date_normalizate)
4. Creati o expresie lambda care va afisa o lista data ca input ridicata la patrat.
ex: my_list = [1, 2, 3] => [1, 4, 9]
# Rezolvare lista = [1, 2, 3, 4] patrat = lambda n: n**2 # Functie care imi ridica un numar n la patrat listaNoua = map(patrat,lista) # Mapez acea functie pentru fiecare element din lista print(list(listaNoua)) # Afisez listaNoua, dar neaparat cu list in fata, altfel imi afiseaza adresa!
5. Sortati urmatoarea lista dupa a 2-a valoare din fiecare tuplu folosind expresii Lambda:
ex: a = [(0, 2), (4, 3), (9, 9), (10, -1)]
sorted_a = [(10, -1), (0, 2), (4, 3), (9, 9)] # Rezolvare a = [(0, 2), (4, 3), (9, 9), (10, -1)] sorted_a = a[:] # Copiez in sorted_a toate elementele din a, pentru a putea realiza sortarea ulterior. Nu pot aplica comanda de sortare direct. sorted_a.sort(key = lambda x:x[1]) # Numerotarea incepe de la 0, am ales 1 intrucat ordonarea se face dupa al doilea element din fiecare tuplu. print(sorted_a) 12
6. Scrieti un program Python pentru a filtra o lista de numere intregi folosind expresii Lambda si functia filter(). ex: orig_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] even_list = [2, 4, 6, 8, 10] odd_list = [1, 3, 5, 7, 9]
# Rezolvare orig_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] odd_list = list(filter(lambda x:x%2==0, orig_list)) # Filtrez elementele din orig_list care respecta conditia din functia lambda, si transform in lista rezultatul even_list = list(filter(lambda x:x%2!=0, orig_list)) # Aidoma print(odd_list) print(even_list)
7. Aveti o listă cu prețuri ale produselor, dar unele sunt None (lipsă). Folositi filter() pentru a elimina elementele None și map() pentru a aplica o reducere de 10%.
# Rezolvare def removeNone(pret): if pret is not None: # Pentru filtrare tot timpul folosim functii care returneaza val booleana. Aici daca pretul nu e None trimitem true ai. sa ramana numai ce nu e None return True else: return False def reducere(pret): return pret - (10/100*pret) # Pentru map se folosesc functii tip returnabile, si trimitem valoarea modificata, aici reducere cu 10 procente listaPreturi = [10, 20, 30, None, 12, None, 3, None] listaPreturi = list(filter(removeNone, listaPreturi)) listaPreturi = list(map(reducere, listaPreturi)) print(listaPreturi)
13TEORIE
x = 2 y = 3 n = 2 x + y # Adunare x - y # Scadere x * y # Inmultire x ** y # Ridicare la putere <=> x^y in C++ x / y # Impartire x // y # Impartire cu trunchiere, rezultatul e nr. intreg x % y # Operatia modulo - rezultatul va fi restul lui x / y pow(x, y) # x^y abs(x) # Modulul lui x round(x) # Rotunjeste pe x, rezultat nr. intreg round(x, n) # Rotunjeste pe x la n zecimala bin(x) # x in baza 2 (binar) hex(x) # x in baza 16 (hexa) range(10) # numerele intregi de la 0 la 9 range(1, 10) # numerele intregi de la 1 la 9 range(0, 10, 2) # numerele intregi de la 0 la 9 din 2 in 2: 0, 2, 4, 6, 8 print(x) # cout<<x - Afisare x = input() # cin>>x - Atribuire ceva in x x = int(x) # In x punem ce am atribuit sub forma de val. intreaga x = float(x) # In x punem ce am atribuit sub forma de val. flotanta (nr real) x = str(x) # In x punem ce am atribuit sub forma de sir de caractere # OBSERVATIE: O sa vedeti ca asa lucram si cu LISTE, TUPLE si SETURI, # trecand de la un tip de date la altul in mod convenabil. nume = "Vladut Vacaru" ## Metode de slicing pentru siruri de caractere nume[2] # a (numaratoarea incepe de la 0!) nume[:] # Vladut Vacaru (afiseaza intreg sirul) nume[1:] # ladut Vacaru (afiseaza de la caracterul de pe poz 1 inclusiv, incolo) nume[:2] # Vl (afiseaza pana la pozitia 2 inclusiv) nume[-1] # u (afiseaza caracterul de pe ultima pozitie) nume[-2] # r (afiseaza caracterul de pe penultima pozitie) nume[::2] # Vau aau (afiseaza caracterele din 2 in 2) nume[::-1] # uracaV tudalV (afiseaza in ordine inversa - functie speciala) nume[0:8:2] # Vau (nume[start:stop:step] adica iau caracterele de la pozitia start inclusiv, pana la stop (stop nu se include), cu pasul step) ## Observatii: Endline-ul se pune automat, nu mai e necesar, cum era in C sa il punem dupa fiecare print ## dar, daca se doreste endl in mod specific -> print("\n") # Concatenare - op. + intre siruri print("Ion " + nume) # Ion Vladut Vacaru # Afisare multipla print(nume * 10) # Vladut Vacaru va fi afisat de 10 ori len(nume) # Numarul de caractere din sir, inclusiv spatiile nume.strip() # Sterge spatiile care sunt la inceput si final, nu si cele din interiorul sirului nume.split() # Genereaza o lista cu toate cuvintele din sir, despartite prin spatiu # OBS: la split, putem adauga "," sau "." in cazul in care pe post de despartitor avem altceva. Daca nu punem nimic, se considera spatiul ca vin despartitor. nume.replace("Vladut", "Ion") # Ion Vacaru (inlocuieste Vladut cu Ion)
nume.startswith("Vladut") # Adev. (puteti sa verificati si cu un singur caracter daca incepe) nume.endswith("Vacaru") # Adev. (la fel, puteti sa verificati si cu un sigur caracter daca se termina) nume.index("V") # pozitia unde se gaseste prima data caracterul V, daca nu gaseste da eroare nume.find("V") # pozitia unde se gaseste prima data caracterul V, daca nu gaseste da -1 nume.count("a") # numarul de aparitii al caracterului a, se poate face si pentru secvente de caractere nume.lower() # vladut vacaru (litere mici) nume.upper() # VLADUT VACARU (litere mari) nume.capitalize() # Vladut vacaru (bun pentru propozitii - incepe cu litera mare si restul pune litera mica) # Ca metoda de afisare in cazul mai multor siruri de caractere sau tipuri de date, recomand urmatoarea forma: print(f"Ma numesc {nume} si am {y} ani.") ## In cazul variabilelor boolene, bool(x) returneaza FALSE numai pentru x = None/False/CEVA NUL (0, lista goala, set gol etc.) lista = [1, 2, 3, 4] len(lista) # 4 - nr elemente din lista lista.index(3) # 2 - pozitia unde se afla elementul 3 lista.count(3) # 1 - nr aparitii ale elementului 3 lista[2] # 3 - elementul de pe pozitia 2 ## Observatie - Slicing-ul listelor se face IDEM elementelor de tip sir de caractere ## Adaugare in liste lista * 2 # elementele din lista de 2 ori lista + [100, 200] # adaugam la lista elementele 100, 200, putem adauga si un singur element (atentie, nu modifica lista denumita "lista") lista.append(100) # adaugam lista elementul 100, aici are loc modificarea listei "lista". atentie, nu putem adauga o intreaga lista dintr-o bucata ca mai sus. # ci adaugam element cu element. lista.extend([100, 200]) # adaugam in lista elementele 100 si 200, lucru care nu se poate cu append. lista se modifica lista.insert(2, "Inserez pe pozitia 2 acest text") # insereaza elementul de dupa virgula pe pozitia dorita si muta celelalte elemente ' '.join(["Vladut", "Vacaru"]) # Creez un sir de caractere cu elementele din lista (trebuie sa fie de tip string), iar inainte de join pun ce vreau sa desparta elementele (spatiu in acest caz) ## Stergere din liste lista.pop() # Stergem ultimul element lista.pop(1) # Stergem elementul de pe pozitia 1 lista.remove(4) # Stergem din lista elementul dintre paranteze la prima lui aparitie #lista.clear() # Stergem toate elementele din lista #del lista # Stergem existenta listei din memorie ## Sortare liste #lista.sort() # Lista este sortata in ordine crescatoare/alfabetica (toate elementele de acelasi tip!) #lista.sort(reverse=True) # Sortata descrescator #lista.reverse() # Inverseaza pozitia elementelor din lista (in oglinda) #sorted(lista) # Se creaza o copie sortata a listei #reversed(lista) # Se creaza o copie inversata a listei ## Copierea unei liste listaCopie = lista.copy() 2
listaCopie = lista[:] ## OBS: Nu se face listaCopie = lista - deoarece prin aceasta linie, noi atribuim listei noi nu elementele din lista veche, ## ci chiar adresa acesteia. Ce inseamna? Fiind la aceasi adresa, daca "lista" sufera modificari, atunci le vom observa si in "listaCopie" ## Operatii cu liste 1 in lista # True daca 1 se gaseste in lista, altfel False #min(lista) # Minimul din lista #max(lista) # Maximul din lista #sum(lista) # Insumeaza elementele din lista (sa fie int sau foat) # Tuple = liste nemodificabile tuple = ('struguri', 'mere', 'pere', 'mere') ## Observatie - in cadrul tuplelor, nu putem adauga sau modifica elemente! Odata ce a fost creata asa ramane! ## Deci interzis tuple[1] = 'gutui' sau tuple.append('visine') tuple[0] # struguri - putem prelua elementele de pe pozitii dorite tuple[-1] # mere - elementul de pe ultima pozitie len(tuple) # 4 - numarul de elemente tuple.index('mere') # pozitia primei aparitii a elementului 'mere' tuple.count('mere') # numarul de aparitii a elementului 'mere' # Seturi = lista cu elemente unice set1 = set() set2 = {1, 2, 3} set1.add(1) # adaug elementul 1 set1.add(2) # adaug elementul 2 set1.add(2) # nu se modifica, deoarece 2 exista deja set1.remove(1) # sterge elementul 1, daca nu exista 1 da eroare set1.discard(1) # sterge elementul 1, daca nu exista 1 nu se intampla nimic set1.clear() # elementele din set sunt sterse set1 = set2.copy() # copiem, situatie similara cu listele set3 = set1.union(set2) # set3 este reuniunea dintre set1 si set2 (elemente comune si necomune, scrise o singura data) set4 = set1.intersection(set2) # set4 este intersectia dintre set1 si set2 (elementele comune) set5 = set1.difference(set2) # sterge elementele ce se gasesc in set1 cat si in set2 si raman celelalte din set1 set6 = set1.symmetric_difference(set2) # sterge elementele ce se gasesc in set1 cat si in set2 si raman celelalte din ambele seturi set1.issubset(set2) # true daca set1 se gaseste integral in set2, false altfel set1.issuperset(set2) # true daca set2 se gaseste integral in set1, false altfel set1.isdisjoint(set2) # true daca set1 si set2 nu au niciun element comun, false altfel ## OBSERVATIE: Putem transforma convenabil listele, seturile si tuplele in ce dorim: set1 = list(set1) tuple = list(tuple) lista = set(lista) tuple = set(tuple) lista = tuple(lista) set1 = tuple(set1) 3
# Dictionare - perechi cheie valoare myDict = {'nume':'Vladut Vacaru', 'varsta':'90', 'situatie':'pensionar', 'in viata':True} myDict['nume'] # Vladut Vacaru - afisez cheia 'nume', daca nu exista cheia, da eroare len(myDict) # 4 - numarul de chei din dictionar list(myDict.keys()) # ['nume', 'varsta', 'situatie', 'in viata'] - afiseaza sub forma unei liste, cheile din dictionar list(myDict.values()) # ['Vladut Vacaru', '90', 'pensionar', True] - afiseaza sub forma unei liste, valorile cheilor din dictionar list(myDict.items()) # afiseaza sub forma de lista, perechi cheie-valoare myDict['par'] = 'carunt' # pot adauga in dict. pereche cheie ('par') valoare ('carunt') myDict.get('varsta') # 90 - asemanator cu myDict['varsta'], dar in acest caz daca nu exista cheia returneaza None myDict.get('prenume', 'NU EXISTA') # trimite valoarea cheii 'prenume', iar daca nu exista cheia, returneaza 'NU EXISTA' del myDict['nume'] # sterg efectiv din memorie cheia 'nume' a dictionarului myDict x == y # true daca egale x is y # true daca x si y sunt la aceeasi adresa! x is not y # true daca x si y nu sunt la aceeasi adresa x != y # true daca inegale x > y x < y x >= y x <= y and # se face intre 2 operatii, true daca ambele sunt adevarate or # la fel, returneaza true daca cel putin o conditie e indeplinita not True # da False x in lista # true daca x se afla in lista, false altfel x not in lista # true daca x nu se afla in lista, false altfel if x in lista: # program1 elif x in listaCopie: # program2 else: #program3 for nr in lista: # In nr se salveaza pe rand elementele din lista, pana la parcurgerea tuturor elementelor print(nr) # In final vor fi afisate toate elementele din lista, pe rand # Se aplica identic si la tuple, si la seturi pentru preluare element cu element for a, b in myDict.items(): # Preiau din dictionar pachet cheie-valoare print(a) # In a salvez cheia print(b) # In b salvez valoarea cheii a while x != y: # program if x < y: break # iese din bucla while else: continue # merge la linia urmatoare 4
# Functii def numeFunctie(x): return sum(x) print(numeFunctie([1,2,3])) ## *args - folosim pentru a trimite tuple ## **kwargs - folosim pentru a trimite dictionare def afisTuple(*tupla): for elem in tupla: print(elem) def afisDict(**dict): for cheie, val in dict.items(): print(f'{cheie} == {val}') tuple = ('struguri', 'mere', 'pere', 'mere') myDict = {'nume':'Vladut Vacaru', 'varsta':'90', 'situatie':'pensionar', 'in viata':True} afisTuple(*tuple) afisDict(**myDict) # LAMBDA Gauss = lambda n : n if n<=1 else n + Gauss(n-1) # Pentru un numar n trimis functiei Gauss, ia valoarea n pentru n<=1, altfel ia valoarea n + Gauss(n-1) - functie recursiva rezultat = Gauss(10) # aplic functia de mai sus pentru nr 10 print(rezultat) # MAP - aplica o functie pentru fiecare element dintr-o lista/set def cub(n): return n**3 numere = [1, 2, 3, 4] numereCub = map(cub, numere) # aplic functia cub pentru fiecare element al listei "numere" print(list(numereCub)) # transform in lista, altfel va afisa adresa # Filter - filtreaza valorile dupa o functie ce returneaza valoare tip boolean - true/false def numereMici(nr): if nr<30: return True else: return False import random numere = [random.randint(1,100) for _ in range(10)] #generez 10 numere pseudorandom intre 1 si 100 numereFiltrate = filter(numereMici, numere) # va selecta practic numerele mai mici decat 30 din lista 'numere' print(list(numereFiltrate)) # la fel, transformam in lista # Reduce - combina toate valorile si genereaza un singur rezultat final, bazat pe o functie, in general lambda import functools numere = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] 5
print(functools.reduce(lambda a, b: a + b, numere)) # 1 + 2 = 3; 3 + 3 = 6; 6 + 4 = 10; 10 + 5 = 15; etc.. Combina rezultatul cu urmatorul element! print(functools.reduce(lambda a, b: a if a>b else b, numere)) # afiseaza numarul maxim # Zip - pentru a intercala date dintre 2 liste / seturi / tuple de pe aceleasi pozitii si produce tupluri de elemente names = ['Ionescu', 'Popescu', 'Vasilescu'] ages = ['23', '32', '41'] for name, age in zip(names, ages): print(name, age) # Se va afisa pe rand: Ionescu 23 Popescu 32 Vasilescu 41 # Comprehensions - ajuta sa construim rapid liste, seturi, tuple, dictionare lista = [i for i in range(10)] # [0, 1, 2, ..., 9] set = {i for i in range(20) if i>=5} # {5, 6, 7, ..., 20} tuple = (i+2 for i in range(10)) # (2, 3, 4, 5, 6, 7, 8, 9, 10, 11) dict = {i: i*2 for i in range(10)} # {0: 0, 1: 2, 2: 4, ... , 9: 18}
6
PROBLEME REZOLVATE
1. Tricky picture: picture = [ [0,0,0,1,0,0,0], [0,0,1,1,1,0,0], [0,1,1,1,1,1,0], [1,1,1,1,1,1,1], [0,0,0,1,0,0,0], [0,0,0,1,0,0,0]]
Haha! Very funny, doamna Claudia! Nu e asa tricky pe cat ziceti dumneavoastra! Va afisa un BRAD FRUMOS! (poza din coltu’ dreapta sus)
# Rezolvare picture = [ [0,0,0,1,0,0,0], [0,0,1,1,1,0,0], [0,1,1,1,1,1,0], [1,1,1,1,1,1,1], [0,0,0,1,0,0,0], [0,0,0,1,0,0,0]] for line in picture: # Parcurg fiecare linie din lista de linii picture (e un fel de matrice) visual = " " # Creez o variabila in care practic voi salva linia modificata for element in line: # Parcurg fiecare element din linie if element == 1: visual = visual + '*' # Modific variabila de linie a.i. daca avem 1 pe o pozitie sa adauge * else: visual = visual + ' ' # Pentru 0, adauga un spatiu print(visual) # Inainte sa treaca la linia urmatoare, afisam linia curenta modificata
2. Scrieți un program care cere utilizatorului să introducă nota unui examen și afișează calificativul conform regulilor: ● 9-10: Excelent ● 7-8: Bine ● 5-6: Suficient ● Sub 5: Reexaminare Dacă utilizatorul introduce o notă invalidă (ex. -3 sau 11), cereți-i să reintroducă o valoare validă. # Rezolvare nota = input("Introduceti nota, domnule sutudent: ") # Introducem nota nota = int(nota) # Trebuie sa asiguram tipul de data, altfel programul nu va deosebi de string! if nota<1 or nota>10: # Mereu recomand a se verifica cazul care genereaza eroare si abia dupa cazurile okay! print("Din ce stiu notele in ROMANIA sunt intre 1 si 10!") elif nota>=9: # Nu am mai pus sa fie si mai mic decat 10, deoarece prin elif sugerez opusul conditiei de mai sus, adica nota<=10 print("Excelent! Esti un student model!") elif nota>=7: # La fel, nu mai fortez sa fie mai mic decat 9, elif imi asigura asta print("Bine dar se poate si mai bine!") elif nota>=5: print("Suficient, ma asteptam la mai mult!") else: print("REEXAMINARE! ESTI TUFA DE VENETIA!") 7
3. Scrieți un program care generează un număr aleatoriu între 1 și 50. Utilizatorul trebuie să ghicească numărul, iar programul oferă feedback: ● "Numărul este mai mare!" dacă utilizatorul a introdus un număr prea mic. ● "Numărul este mai mic!" dacă utilizatorul a introdus un număr prea mare. ● "Felicitări! Ai ghicit!" dacă numărul a fost găsit. # Rezolvare import random # Pentru valori aleatorii, trebuie import la fct. random numarAleator = random.randint(1,50) # General un nr pseudorandom intre 1 si 50 inclusiv numarAles = 0 # Initializez numarAles cu 0, care sigur nu e intre 1 si 50, pentru a face citirile in while strict while numarAles!=numarAleator: # Cat timp sunt diferite, stam in while numarAles=input("Introduceti numarul, domnule: ") # Numarul va fi introdus cat timp stam in bucla numarAles=int(numarAles) # Se transforma in int pentru a fi siguri ca nu este tratat ca string! if numarAles>numarAleator: # Verificam daca e mai mare, mai mic sau egal print("Numarul este mai mic!") elif numarAles<numarAleator: print("Numarul este mai mare!") else: print("FELICITARI! ATI GHICIT!")
4. Creați o listă de orașe și parcurgeți-o folosind enumerate(), astfel încât să afișați fiecare oraș numerotat. Exemplu de rulare: 1. București 2. Cluj-Napoca 3. Timișoara 4. Iași # Rezolvare orase = ['Bucuresti', 'Cluj-Napoca', 'Timisoara', 'Iasi'] # Creez lista conform cerintei for i, oras in enumerate(orase): # Aici i va fi ca un index, ia pozitia pentru fiecare element preluat din lista print(f"{i+1}. {oras}") # Am pus i+1, deoarece o lista incepe cu pozitia 0, si eu vreau sa am 1. Bucuresti 2. Cluj-Napoca...
8
5. Un utilizator participă la o loterie în care trebuie să aleagă un set de numere, iar programul generează numere câștigătoare. ● Utilizatorul își alege 6 numere între 1 și 49. ● Programul generează 6 numere aleatorii (simulând extragerea loteriei). ● Se compară numerele alese cu cele extrase. ● Se afișează câte numere a ghicit și un mesaj de câștig. Exemplu de rulare: Bine ai venit la Loteria Python! Alege 6 numere între 1 și 49. ● Numărul 1: 7 ● Numărul 2: 15 ● Numărul 3: 23 ● Numărul 4: 31 ● Numărul 5: 40 ● Numărul 6: 45
Numere extrase: [12, 7, 31, 23, 8, 40]
Ai ghicit 3 numere: [7, 23, 31]
Felicitări! Ai câștigat un premiu mic!
# Rezolvare import random # Declar liste necesare programului numereCastigatoare = [] numereAlese = [] numereGhicite = [] print('Bine ai venit la LOTO 6/49 \n') print('Alege 6 numere intre 1 si 49 \n') for i in range(6): # Pentru i de la 0 la 5, merg 6 pasi numarCurent = input(f'- Numarul {i+1}: ') # Am pus i+1 pentru ca i merge de la 0, si sa inceapa ordinea numerelor de la 1 numarCurent = int(numarCurent) # Mereu sa faceti trecerea la int, altfel va treziti cu string-uri! numereAlese.append(numarCurent) # Adaug in lista numarul curent selectat, la finalul for-ului voi avea toate cele 6 numere alese for i in range(6): numereCastigatoare.append(random.randint(1,49)) # Se simuleaza extragerea pe rand a unui numar aleatoriu intre 1 si 49 si il adaug in lista. for i in numereAlese: # Parcurg lista cu numere alese pentru a plasa in vectorul numereGhicite numerele alese care sunt si castigatoare if i in numereCastigatoare: # Daca numarul ales se afla in lista de numereCastigatoare, atunci adaug acel numar si in lista numereGhicite numereGhicite.append(i) print(f'Numere extrase: {numereAlese}') # Afisez numere extrase print(f'Ai ghicit {len(numereGhicite)} numere! {numereGhicite}') # Afisez nr de numere ghicite respectiv lista cu ele if len(numereGhicite) == 6: print("FELICITARI! ATI CASTIGAT PREMIUL CEL MARE!") elif len(numereGhicite) >= 4: print("Felicitari! Aticastigat un premiu mic") else: print("Ne pare rau! Ati pierdut! Mergeti acas'!") 9
6. Scrieți un program care simulează o aventură într-o pădure magică. Utilizatorul trebuie să aleagă între două direcții (stânga sau dreapta). În funcție de alegere, programul prezintă evenimente diferite (ex. întâlnirea unui lup, descoperirea unei comori). Adăugați mai multe evenimente, inclusiv un inventar pentru obiectele găsite.
Deja e vorba de creativitate. Creati liste cu evenimente, cream si un dictionar care e pe post de inventar sa zicem cu cheie armura, sabie, ce va vine in minte, iar ca valori ale acelor chei punem True/False. In rest, 1000 de if-uri, ca la parada! Puteti avea evenimente mai randomizate, sa folositi si functie de tip random.choice care sa aleaga un eveniment random din lista de evenimente creata de voi. Problema nu este dificila, doar necesita multa rabdare. Atasez exemplu cu AI:
import random # folosim random pentru evenimente aleatorii # dicționar cu evenimente posibile pe direcții evenimente = { "s": ["Ai întâlnit un lup 🐺", "Ai găsit o comoară 💰", "Ai căzut într-o groapă! 😵"], "d": ["Ai găsit o poiană 🌿", "Ai întâlnit un spiriduș 🧝", "Ai descoperit o peșteră 🕳️"] } # inventar sub formă de dicționar (obiect -> cantitate) inventar = {} print("🌲 Bine ai venit în Pădurea Magică!") print("Comenzi: s = stânga, d = dreapta, q = ieșire") # funcție mică pentru a adăuga obiecte în inventar def adauga_inventar(obiect): # dacă obiectul există deja în dicționar if obiect in inventar: inventar[obiect] += 1 # creștem cantitatea else: inventar[obiect] = 1 # îl adăugăm prima dată while True: # bucla principală a jocului alegere = input("\nAlege direcția (s/d/q): ") if alegere == "q": print("👋 Ai ieșit din pădure. Inventar final:", inventar) break if alegere in evenimente: # verificăm dacă e s sau d eveniment = random.choice(evenimente[alegere]) # alegem un eveniment random print("👉 Eveniment:", eveniment) # analizăm evenimentul și modificăm inventarul if "comoară" in eveniment: print("💰 Ai găsit aur!") adauga_inventar("aur") elif "spiriduș" in eveniment: print("🪄 Spiridușul ți-a dat o baghetă magică!") adauga_inventar("baghetă magică") elif "peșteră" in eveniment: print("🪨 Ai găsit o piatră misterioasă!") adauga_inventar("piatră misterioasă") elif "lup" in eveniment: print("🐺 Ai fugit de lup!") elif "groapă" in eveniment: print("😵 Ai căzut, dar te-ai ridicat!") # afișăm inventarul după fiecare pas print("🎒 Inventar:", inventar) else: print("❌ Comandă invalidă! Folosește s, d sau q.") 10
7. Creează un program care analizează tonul unui comentariu introdus de utilizator. ● Dacă un comentariu conține cuvinte pozitive (["bine", "frumos", "super", "excelent", "minunat"]), afișează "Comentariu pozitiv!". ● Dacă conține cuvinte negative (["urât", "prost", "groaznic", "dezamăgitor"]), afișează "Comentariu negativ!". ● Dacă nu se detectează niciun sentiment clar, afișează "Comentariu neutru.".
# Rezolvare comentariu = input('Ce mesaj transmiteti actualilor guvernanti ai Romaniei? Va rugam sa argumentati: ') # Definesc listele cu cuvintele aferente cuvintePozitive = ["bine", "frumos", "super", "excelent", "minunat"] cuvinteNegative = ["urat", "prost", "groaznic", "dezamăgitor"] if any(cuvant in comentariu.lower() for cuvant in cuvinteNegative): # Logica e: ia fiecare cuvant din lista cuvinteNegative si cauta daca se gaseste acea secventa in sirul de caractere "comentariu", # l-am pus lower pentru a ma asigura ca am idem cu ce se gaseste in lista cuvinteNegative print("Comentariu negativ!") elif any(cuvant in comentariu.lower() for cuvant in cuvintePozitive): # Logica e aceeasi, dar pentru lista cuvintePozitive print("Comentariu pozitiv!") else: print("Comentariu neutru.")
1. Creati un joc Rock-Paper-Scissors pentru doi jucatori. (Hint: Solicitati selectia jucatorilor (folosind input), comparati alegerile lor, afisati un mesaj de felicitari pentru castigator si intreabati daca jucatorii doresc sa inceapa un nou joc).
Tine minte regulile:
● Piatra bate foarfeca
● Foarfeca taie hartia
● Hartia bate piatra
# Rezolvare # Efectiv if-uri pentru toate cazurile! print("Bine ai venit la jocul Piatra-Hartie-Foarfeca!") Jucator1 = input("Jucator 1 alege: ") Jucator2 = input("Jucator 2 alege: ") if Jucator1.lower() == "piatra": if Jucator2.lower() == "piatra": print("REMIZA!") elif Jucator2.lower() == "hartie": print("Jucator 2 CASTIGA!") else: print("Jucator 1 CASTIGA!") if Jucator1.lower() == "hartie": if Jucator2.lower() == "piatra": print("Jucator 1 CASTIGA") elif Jucator2.lower() == "hartie": print("REMIZA!") else: print("Jucator 2 CASTIGA!") if Jucator1.lower() == "foarfeca": if Jucator2.lower() == "piatra": print("Jucator 2 CASTIGA") elif Jucator2.lower() == "hartie": print("Jucator 1 CASTIGA") else: print("REMIZA!") 11
2. Scrieti o funcție genereaza_factura() care acceptă numele clientului, și un număr variabil de produse și prețuri folosind **kwargs.
# Rezolvare def genereaza_factura(**kwargs): # La dictionare, folosim kwargs! for cheie, val in kwargs.items(): # Pentru a prelua perechea cheie-valoare, pe care le afisam print(f"{cheie}: {val}") cumparaturi_Popescu = {'Nume': 'Ionescu Popescu', 'Lapte': '10 RON', 'Piept de pui': '25 RON', 'WINSTON SLIM': '30 RON'} genereaza_factura(**cumparaturi_Popescu)
3. Scrieți o funcție care normalizează datele dintr-o listă într-un interval [0,1].
● Funcția trebuie să accepte o listă de numere și să returneze lista normalizată.
● Testați funcția pe un set de date aleator.
ex:data = [10, 20, 30, 40, 50]
normalized_data = normalize_data(data)
print(normalized_data) # Output: [0.0, 0.25, 0.5, 0.75, 1.0]
# Rezolvare def normalizare(dates): dates_new = [] maxim = max(dates) minim = min(dates) for data in dates: data_new = (data-minim)/(maxim-minim) # Pentru fiecare numar aplicam formula aceasta - formula standard pentru normalizare dates_new.append(data_new) return dates_new date = [10, 20, 30, 40, 50] date_normalizate = normalizare(date) print(date_normalizate)
4. Creati o expresie lambda care va afisa o lista data ca input ridicata la patrat.
ex: my_list = [1, 2, 3] => [1, 4, 9]
# Rezolvare lista = [1, 2, 3, 4] patrat = lambda n: n**2 # Functie care imi ridica un numar n la patrat listaNoua = map(patrat,lista) # Mapez acea functie pentru fiecare element din lista print(list(listaNoua)) # Afisez listaNoua, dar neaparat cu list in fata, altfel imi afiseaza adresa!
5. Sortati urmatoarea lista dupa a 2-a valoare din fiecare tuplu folosind expresii Lambda:
ex: a = [(0, 2), (4, 3), (9, 9), (10, -1)]
sorted_a = [(10, -1), (0, 2), (4, 3), (9, 9)] # Rezolvare a = [(0, 2), (4, 3), (9, 9), (10, -1)] sorted_a = a[:] # Copiez in sorted_a toate elementele din a, pentru a putea realiza sortarea ulterior. Nu pot aplica comanda de sortare direct. sorted_a.sort(key = lambda x:x[1]) # Numerotarea incepe de la 0, am ales 1 intrucat ordonarea se face dupa al doilea element din fiecare tuplu. print(sorted_a) 12
6. Scrieti un program Python pentru a filtra o lista de numere intregi folosind expresii Lambda si functia filter(). ex: orig_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] even_list = [2, 4, 6, 8, 10] odd_list = [1, 3, 5, 7, 9]
# Rezolvare orig_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] odd_list = list(filter(lambda x:x%2==0, orig_list)) # Filtrez elementele din orig_list care respecta conditia din functia lambda, si transform in lista rezultatul even_list = list(filter(lambda x:x%2!=0, orig_list)) # Aidoma print(odd_list) print(even_list)
7. Aveti o listă cu prețuri ale produselor, dar unele sunt None (lipsă). Folositi filter() pentru a elimina elementele None și map() pentru a aplica o reducere de 10%.
# Rezolvare def removeNone(pret): if pret is not None: # Pentru filtrare tot timpul folosim functii care returneaza val booleana. Aici daca pretul nu e None trimitem true ai. sa ramana numai ce nu e None return True else: return False def reducere(pret): return pret - (10/100*pret) # Pentru map se folosesc functii tip returnabile, si trimitem valoarea modificata, aici reducere cu 10 procente listaPreturi = [10, 20, 30, None, 12, None, 3, None] listaPreturi = list(filter(removeNone, listaPreturi)) listaPreturi = list(map(reducere, listaPreturi)) print(listaPreturi)
13
8. Scrieti un program pentru a extrage anul, luna, data si ora folosind Lambda.
ex: 2023-04-24 09:03:32.744178 2023 04 24 09:03:32.744178 # Rezolvare acum = "2023-04-24 09:03:32.744178" data = acum.split(" ")[0] # acum.split(" ") genereaza o lista cu 2 elemente ce erau despartite prin " ", prima va fi data pe poz 0 si a doua va fi ora exacta pe poz 1 ora = acum.split(" ")[1] anul = data.split("-")[0] # splituiesc data in an, luna si ziua care sunt despartite prin "-", pe poz 0 am anul, pe 1 luna si pe 2 ziua luna = data.split("-")[1] ziua = data.split("-")[2] print(anul) print(luna) print(ziua) print(ora)
9. Să presupunem că aveți două liste de numere și doriți să creați o funcție care va returna o listă de tupluri în care fiecare tuplu va conține suma elementelor corespunzătoare din cele două liste. Pentru a face acest lucru, veți utiliza funcția zip() pentru a itera prin cele două liste și a aduna elementele corespunzătoare.
list1 = [1, 2, 3, 4, 5] list2 = [10, 20, 30, 40, 50]
result = sum_lists(list1, list2) print(result) # Output: [11, 22, 33, 44, 55]
# Rezolvare def suma(lista1, lista2): listaNoua = [] for x, y in zip(lista1, lista2): listaNoua.append(x+y) return listaNoua list1 = [1, 2, 3, 4, 5] list2 = [10, 20, 30, 40, 50] rezultat = suma(list1, list2) print(rezultat)
10. List Comprehension: ● Creati o lista cu numere pare de la 0 la 100. [] ● Creati o lista care contine cuburile primelor 10 numere intregi. ● Creati o lista care contine toate elementele comune din doua liste date.
# Rezolvare list1 = [i for i in range(100) if i%2==0] list2 = [i**3 for i in range(10)] list3 = [element for element in list1 if element in list2] # Preiau elementele din lista1 doar daca se afla si in lista2 print(list1) print(list2) print(list3) 11. Set Comprehension: 14
● Creati un set care contine primele 10 numere pare. {} ● Creati un set care contine toate literele distincte dintr-un string dat. ● Creati un set care preia cuvantul cheie dintr-un set existent, daca acel cuvant cheie exista in setul respectiv.
# Rezolvare myset = (i*2 for i in range(10)) cuvant = "Sarbatori binecuvantate alaturi de cei dragi" litereCuv = (litera for litera in cuvant) cuvCheie = (cuv for cuv in cuvant.split(" ") if cuv=="Sarbatori") print(list(myset)) print(list(litereCuv)) print(list(cuvCheie))
12. Dictionary Comprehension: {key:value} ● Creati un dictionar cu numerele de la 1 la 10 ca si chei si patratelele lor ca si valori. ● Creati un dictionar care contine literele unui string dat ca si chei si numarul de aparitii ale fiecarei litere ca si valori. ● Creati un dictionar care contine primele 10 numere intregi ca si chei si lista lor de divizori ca si valori.
# Rezolvare dict1 = {i: i**2 for i in range(1,11)} # Ce e inainte de : reprezinta cheia, iar dupa : avem valoarea, adica i^2 pentru toti i intre 1 si 10, am pus 11 pentru ca merge pana la 11-1 propozitie = "Paste fericit alaturi de cei dragi. Sarbatori pascale in tihna, cu liniste si pace" dict2 = {litera: propozitie.count(litera) for litera in propozitie} # Cheia este litera corespunzatoare, iar valoarea este numarul de aparitii a literei in sirul de caractere Prorpozitie dict3 = {i:len([j for j in range(1,i) if i%j==0])+1 for i in range(10)} # Cheia este i iar valoarea este lungimea unei liste care retine numarul de divizori ai lui i la care adaug 1 pentru ca merge pana la i-1, deci nu il ia si pe el insusi ca divizor print(dict1) print(dict2) print(dict3) 15
8. Scrieti un program pentru a extrage anul, luna, data si ora folosind Lambda.
ex: 2023-04-24 09:03:32.744178 2023 04 24 09:03:32.744178 # Rezolvare acum = "2023-04-24 09:03:32.744178" data = acum.split(" ")[0] # acum.split(" ") genereaza o lista cu 2 elemente ce erau despartite prin " ", prima va fi data pe poz 0 si a doua va fi ora exacta pe poz 1 ora = acum.split(" ")[1] anul = data.split("-")[0] # splituiesc data in an, luna si ziua care sunt despartite prin "-", pe poz 0 am anul, pe 1 luna si pe 2 ziua luna = data.split("-")[1] ziua = data.split("-")[2] print(anul) print(luna) print(ziua) print(ora)
9. Să presupunem că aveți două liste de numere și doriți să creați o funcție care va returna o listă de tupluri în care fiecare tuplu va conține suma elementelor corespunzătoare din cele două liste. Pentru a face acest lucru, veți utiliza funcția zip() pentru a itera prin cele două liste și a aduna elementele corespunzătoare.
list1 = [1, 2, 3, 4, 5] list2 = [10, 20, 30, 40, 50]
result = sum_lists(list1, list2) print(result) # Output: [11, 22, 33, 44, 55]
# Rezolvare def suma(lista1, lista2): listaNoua = [] for x, y in zip(lista1, lista2): listaNoua.append(x+y) return listaNoua list1 = [1, 2, 3, 4, 5] list2 = [10, 20, 30, 40, 50] rezultat = suma(list1, list2) print(rezultat)
10. List Comprehension: ● Creati o lista cu numere pare de la 0 la 100. [] ● Creati o lista care contine cuburile primelor 10 numere intregi. ● Creati o lista care contine toate elementele comune din doua liste date.
# Rezolvare list1 = [i for i in range(100) if i%2==0] list2 = [i**3 for i in range(10)] list3 = [element for element in list1 if element in list2] # Preiau elementele din lista1 doar daca se afla si in lista2 print(list1) print(list2) print(list3) 11. Set Comprehension: 14
● Creati un set care contine primele 10 numere pare. {} ● Creati un set care contine toate literele distincte dintr-un string dat. ● Creati un set care preia cuvantul cheie dintr-un set existent, daca acel cuvant cheie exista in setul respectiv.
# Rezolvare myset = (i*2 for i in range(10)) cuvant = "Sarbatori binecuvantate alaturi de cei dragi" litereCuv = (litera for litera in cuvant) cuvCheie = (cuv for cuv in cuvant.split(" ") if cuv=="Sarbatori") print(list(myset)) print(list(litereCuv)) print(list(cuvCheie))
12. Dictionary Comprehension: {key:value} ● Creati un dictionar cu numerele de la 1 la 10 ca si chei si patratelele lor ca si valori. ● Creati un dictionar care contine literele unui string dat ca si chei si numarul de aparitii ale fiecarei litere ca si valori. ● Creati un dictionar care contine primele 10 numere intregi ca si chei si lista lor de divizori ca si valori.
# Rezolvare dict1 = {i: i**2 for i in range(1,11)} # Ce e inainte de : reprezinta cheia, iar dupa : avem valoarea, adica i^2 pentru toti i intre 1 si 10, am pus 11 pentru ca merge pana la 11-1 propozitie = "Paste fericit alaturi de cei dragi. Sarbatori pascale in tihna, cu liniste si pace" dict2 = {litera: propozitie.count(litera) for litera in propozitie} # Cheia este litera corespunzatoare, iar valoarea este numarul de aparitii a literei in sirul de caractere Prorpozitie dict3 = {i:len([j for j in range(1,i) if i%j==0])+1 for i in range(10)} # Cheia este i iar valoarea este lungimea unei liste care retine numarul de divizori ai lui i la care adaug 1 pentru ca merge pana la i-1, deci nu il ia si pe el insusi ca divizor print(dict1) print(dict2) print(dict3) 15